### ISSUE TITLE
When the connection mode is serial port connection, the viewer cannot receive the message from the daemon.

### ISSUE THREAD

**Issue by Gonglja** [GENIVI/dlt-viewer#65] opened 2019-10-31 02:24 UTC
Hi, developer
I tried to use dlt-viewer on the ubuntu pc side, and run the dlt-daemon and log demo program on the pc side. The tcp network communication can receive the message from the dlt-daemon, but when I use the serial port, I can't receive the message. .
The hardware connection status is as follows: pc side uses two usb to ttl module, tx connects to rx, rx connects to tx, common GND.
Software configuration: dlt.cfg
RS232DeviceName = ttyUSB0
Add RS232Baudrate = 115200  
already open,
The dlt-viewer is configured as a serial port connection, the port is ttyUSB1, and the baud rate is 115200.
![image](https://user-images.githubusercontent.com/39959756/67913609-9d252900-fbc8-11e9-8f73-3e59ad3b8b3c.png)

![image](https://user-images.githubusercontent.com/39959756/67913568-7c5cd380-fbc8-11e9-925f-4415c76db362.png)

Ps: We use the serial port debugging assistant can be connect both two peripherals normally.

**Comment by Gonglja** [comment] 2019-11-01 01:12
Linux use ubuntu16.04

**Comment by alexmucde** [comment] 2019-11-15 08:22
@Gonglja Ubuntu 16.04 already reached end of life, but we will try to reproduce with Ubuntu 18.04.

Duplicate of #55

**Comment by Gonglja** [comment] 2019-11-20 12:33
ths, developer, very helpless, because the project was developed in ubuntu16.04, the customer is also using ubuntu16.04，all in ubuntu16.04...

**Comment by alexmucde** [comment] 2019-11-22 16:47
Looks like configuration issue, see also #55

**Closed by alexmucde** 2019-11-22 16:47 UTC
Labels: help wanted
